<script setup lang="ts">
import { SignedIn, SignedOut } from 'vue-clerk';

const emit = defineEmits<{
  (e: 'register'): void;
  (e: 'new'): void;
}>();

const redirectToStripe = () => {
  window.location.href = 'https://buy.stripe.com/test_aEUaFOakncLnekMeUU'; // Replace with your generated Stripe payment link
};
</script>

<template>
  <div
    class="w-full h-[calc(100vh-300px)] text-center px-5 flex flex-col justify-center items-center gap-2"
  >
    <h1 class="text-4xl font-[700] text-gray-700">
      Generate audio for
      <span class="bg-indigo-500 text-white px-2">
        promotion in just a click!
      </span>
      .
    </h1>
    <p class="text-2xl text-gray-700">
      Increase your market's revenue with audio for promotions <br />
      generated by artificial intelligence.
    </p>

    <SignedOut>
      <Button
        class="mt-5"
        label="Start now"
        icon="pi pi-plus"
        @click="() => emit('register')"
      />
    </SignedOut>

    <SignedIn>
      <Button
        class="mt-5"
        label="Start now"
        icon="pi pi-plus"
        @click="redirectToStripe"
      />
    </SignedIn>
  </div>
</template>
