<script setup lang="ts">
const emit = defineEmits<{
  (e: 'register'): void;
  (e: 'new'): void;
}>();
</script>

<template>
  <div
    class="w-full h-[calc(100vh-300px)] text-center px-5 flex flex-col justify-center items-center gap-2"
  >
    <h1 class="text-4xl font-[700] text-gray-700">
      Generate audio for
      <span class="bg-indigo-500 text-white px-2"
        >promotion in just a click!</span
      >.
    </h1>
    <p class="text-2xl text-gray-700">
      Increase your market's revenue with audio for promotions <br />
      generated by artificial intelligence.
    </p>

    <!--
      <Button
        class="mt-5"
        label="Nova geração"
        icon="pi pi-plus"
        @click="() => emit('new')"
      />
    -->

    <Button
      class="mt-5"
      label="Start now"
      icon="pi pi-plus"
      @click="() => emit('register')"
    />
  </div>
</template>
